CREATE TABLE AIRPORT.DAILY_PSG (
	AIRPORT_NAME VARCHAR(8) NOT NULL COMMENT 'ARP: 공항명(김포공항=GMP, 제주공항=CJU, 김해공항=PUS 등)',
	YYYYMMDD VARCHAR(8) NOT NULL COMMENT 'SDT: 운항일자(YYYYMMDD 형식)',
    HH_HOUR INT COMMENT 'HH: 시간대 정보(HH 형식)',
    PASSENGER_AMT INT COMMENT 'PCT: 예상승객 수(단위: 명)',
    PASSENGER_TEAM_AMT INT COMMENT 'PCG: 단체승객 수(단위: 명)',
    TYPE_OF_FLIGHT VARCHAR(4) COMMENT 'TOF: 국내국제구분 (D=국내, I=국제, N=구분값없음)',
    CONGETST_YN VARCHAR(4) COMMENT 'CONGEST_YN: 혼잡여부(Y=혼잡, N=원활)'
);